/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/almanac": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Hijri almanac: observances and chronicle events.
         * @description Return the full almanac; the client selects for its own "today".
         */
        get: operations["get_almanac_api_almanac_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books with pagination, optionally filtered by category slug.
         * @description Wrap the repo's (slice, total) into a Page[Book] envelope.
         */
        get: operations["_list_books_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_urn}/pages/{page_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one page of book content.
         * @description Return the requested page or raise ``ResourceNotFoundError``.
         *
         *     Structured ``hadiths`` (isnad + matn + narrators) come from the manuscript
         *     index built by Phase 3 extract, via ``manuscript.hadiths_for_page``. When the
         *     page has parsed hadiths they are served and ``text_ar`` is ``None`` (the two
         *     are mutually exclusive per the ``BookPage`` contract); otherwise ``text_ar``
         *     carries the raw page text honestly — for prose pages, or before the index is
         *     built. ``text_en`` is the single wiring point for an English rendering: the
         *     corpus has no English column yet, so it stays ``None`` and the reader shows a
         *     labelled preview; set it here the moment translations land.
         */
        get: operations["get_page_api_books__book_urn__pages__page_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_urn}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search within a book's text (diacritic- + letter-variant-insensitive).
         * @description Scan ``book_urn``'s own pages for ``q`` (the in-memory path; see
         *     ``repositories.corpus.search_in_book``) and wrap the matches in a page.
         */
        get: operations["_search_book_api_books__book_urn__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_urn}/toc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the table of contents for a book.
         * @description Return the TOC for ``book_urn`` or raise ResourceNotFoundError.
         */
        get: operations["get_toc_api_books__book_urn__toc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{urn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single book by URN.
         * @description Return the book with the given URN, or raise ResourceNotFoundError.
         */
        get: operations["get_book_api_books__urn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{urn}/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every volume of the work containing this book, ascending.
         * @description Return every volume of the work containing ``urn``, ascending by volume
         *     number: the reader's volume switcher. A single-volume work returns just
         *     that book. The membership comes from the same fold :func:`list_works`
         *     serves, so the two views can never disagree; a fold entry missing from the
         *     index would be an invariant breach and raises KeyError loudly.
         */
        get: operations["list_volumes_api_books__urn__volumes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canonical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List canonical narrator profiles with pagination + filters.
         * @description Wrap the repo's (slice, total) into a Page[CanonicalEntry] envelope.
         */
        get: operations["_list_canonical_api_canonical_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canonical/{canonical_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single canonical profile by id.
         * @description Return one canonical profile by id, or raise ``ResourceNotFoundError``.
         */
        get: operations["get_canonical_api_canonical__canonical_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's verse, hadith, and book pick, rotated by date.
         * @description Return the Daily selection for the current UTC date.
         */
        get: operations["get_today_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all knowledge domains and their categories.
         * @description Return all domains with their categories, counts + tradition overlaid from
         *     the live catalogue. Stable order.
         */
        get: operations["list_domains_api_domains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quran/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Qurʾān verses containing an Arabic term or phrase.
         * @description Wrap the repo's ``(slice, total)`` of matching ayat into a Page[Ayah].
         */
        get: operations["_search_verses_api_quran_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quran/{surah}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a full surah to its numbered ayat, in order.
         * @description Resolve a surah number to its full run of numbered ayat, in order.
         *
         *     The prefatory basmala (key ``0``) is skipped, matching the search index:
         *     it is not a numbered ayah.
         */
        get: operations["get_surah_api_quran__surah__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quran/{surah}/{ayah}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a Qurʾān verse by surah:ayah reference.
         * @description Resolve a surah:ayah reference to its verse text (both pointed + bare).
         */
        get: operations["get_verse_api_quran__surah___ayah__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rijal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List rijal narrators with pagination + filters.
         * @description Wrap the repo's (slice, total) into a Page[RijalEntry] envelope.
         */
        get: operations["_list_rijal_api_rijal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rijal/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single rijal entry by id.
         * @description Return one rijal entry by id, or raise ``ResourceNotFoundError``.
         */
        get: operations["get_rijal_api_rijal__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across all book content (diacritic-insensitive).
         * @description Wrap the repo's (slice, total) into a Page[CorpusMatch] envelope.
         */
        get: operations["_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Category -> book -> volume filters available for a search query.
         * @description Return the categories, books, and volumes that hold matches for ``q``.
         */
        get: operations["_search_facets_api_search_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List volume-folded works, optionally filtered by category, domain, or tradition.
         * @description Wrap the repo's (slice, total) of works into a Page[Work] envelope.
         */
        get: operations["_list_works_api_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Container health probe — succeeds when the process is up.
         */
        get: operations["_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Livez
         * @description Kubernetes liveness probe.
         */
        get: operations["_livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Kubernetes readiness probe.
         */
        get: operations["_readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Almanac
         * @description The served almanac: every observance + every chronicle entry.
         */
        Almanac: {
            /** Events */
            events: components["schemas"]["HistoryEvent"][];
            /** Observances */
            observances: components["schemas"]["Observance"][];
        };
        /**
         * Ayah
         * @description One Qurʾān verse, resolved from a surah:ayah reference.
         *
         *     ``text_ar`` carries the diacritized recitation text; ``text_plain`` is the
         *     same verse with vowel marks stripped, so a reader sees both the pointed and
         *     the bare forms that corpus quotations may use. The diacritic-insensitive
         *     matching against book content is handled by the search FTS tokenizer, so
         *     either form locates the same passages.
         */
        Ayah: {
            /**
             * Ayah
             * @description Ayah number within the surah.
             */
            ayah: number;
            /**
             * Surah
             * @description Surah number.
             */
            surah: number;
            /**
             * Text Ar
             * @description Verse text with diacritics.
             */
            text_ar: string;
            /**
             * Text En
             * @description English rendering, if available.
             */
            text_en?: string | null;
            /**
             * Text Plain
             * @description Verse text with diacritics stripped.
             */
            text_plain: string;
            /**
             * Verse Count
             * @description Total ayat in the surah.
             */
            verse_count: number;
        };
        /**
         * Book
         * @description One book record (a single physical volume) exposed by the screens.
         */
        Book: {
            /**
             * Author
             * @description Author in romanized form.
             */
            author?: string | null;
            /**
             * Author Ar
             * @description Author in Arabic.
             */
            author_ar: string;
            /**
             * Blurb
             * @description One-sentence editorial summary, if any.
             */
            blurb?: string | null;
            /**
             * Canonical
             * @description Editorial rank, or None.
             */
            canonical?: ("primary_reference" | "primary" | "secondary" | "tertiary") | null;
            /**
             * Category
             * @description Category slug (matches Domain.categories[].slug).
             */
            category: string;
            /**
             * Death Year Ah
             * @description Author's death year, Hijri (unknown is None, never a sentinel).
             */
            death_year_ah?: number | null;
            /**
             * Death Year Ce
             * @description Author's death year, CE.
             */
            death_year_ce?: number | null;
            /**
             * Language
             * @description Primary language of the text.
             * @default Arabic
             */
            language: string;
            /**
             * Madhab
             * @description Madhab when applicable.
             */
            madhab?: string | null;
            /**
             * Page Count
             * @description Page count, if known.
             */
            page_count?: number | null;
            /**
             * Sect
             * @description Sect tagging (Imami, Sunni, etc.).
             */
            sect?: string | null;
            /**
             * Title Ar
             * @description Arabic title.
             */
            title_ar: string;
            /**
             * Title En
             * @description English title, if available.
             */
            title_en?: string | null;
            /**
             * Urn
             * @description Opaque URN identifying the book across screens.
             */
            urn: string;
            /**
             * Volume
             * @description Volume number, if multi-volume.
             */
            volume?: number | null;
        };
        /**
         * BookFacet
         * @description How many matches a book (work, by title) holds, for the book filter.
         */
        BookFacet: {
            /**
             * Count
             * @description Matching pages in this book across its volumes.
             */
            count: number;
            /**
             * Title
             * @description Arabic book title (groups a work's volumes); the filter key.
             */
            title: string;
            /**
             * Title En
             * @description English book title, for display.
             */
            title_en?: string | null;
        };
        /**
         * BookPage
         * @description One book page: parsed hadiths, or raw page text when none are parsed yet.
         */
        BookPage: {
            /** Chapter Title */
            chapter_title: string;
            /** Chapter Title En */
            chapter_title_en?: string | null;
            /** Hadiths */
            hadiths: components["schemas"]["Hadith"][];
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title: string;
            /** Section Title En */
            section_title_en?: string | null;
            /**
             * Text Ar
             * @description Raw page text in Arabic, present when the pipeline has not parsed the page into structured hadiths. Mutually exclusive with a populated hadiths list; never both.
             */
            text_ar?: string | null;
            /**
             * Text En
             * @description English translation of the raw page text, paired with text_ar. None until the pipeline emits a translation for the page; the reader shows a labelled preview in that case and this real text the moment it arrives.
             */
            text_en?: string | null;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * BookSearchMatch
         * @description One in-book search hit: the page and a short Arabic excerpt.
         */
        BookSearchMatch: {
            /**
             * Page
             * @description Page the match occurs on.
             */
            page: number;
            /**
             * Snippet
             * @description Excerpt of the matching unit (Arabic).
             */
            snippet: string;
        };
        /**
         * CanonicalEntry
         * @description A canonicalized person, merging one identity across sources.
         */
        CanonicalEntry: {
            /**
             * Birth Year
             * @description Birth year, Hijri, when known.
             */
            birth_year?: number | null;
            /**
             * Canonical Id
             * @description Stable canonical identity id + detail-route key.
             */
            canonical_id: number;
            /**
             * Death Year
             * @description Death year, Hijri, when known.
             */
            death_year?: number | null;
            /**
             * Entry Count
             * @description Raw corpus entries merged into this identity.
             */
            entry_count: number;
            /**
             * Full Name
             * @description Full name in Arabic.
             */
            full_name: string;
            /**
             * Kunya
             * @description Teknonym (Abu/Umm ...), if recorded.
             * @default
             */
            kunya: string;
            /**
             * Merge Confidence
             * @description Merge confidence in 0..1, or null when unscored.
             */
            merge_confidence?: number | null;
            /**
             * Nisba
             * @description Attributive name (tribe/place), if recorded.
             * @default
             */
            nisba: string;
            /**
             * Source Count
             * @description Distinct source works contributing entries.
             */
            source_count: number;
            /**
             * Student Count
             * @description Union of recorded students across entries.
             */
            student_count: number;
            /**
             * Teacher Count
             * @description Union of recorded teachers across entries.
             */
            teacher_count: number;
            /**
             * Tradition
             * @description Sunni / shia / both, when classified.
             * @default
             */
            tradition: string;
        };
        /**
         * Category
         * @description One category leaf under a domain in the IA taxonomy.
         */
        Category: {
            /**
             * Count
             * @description Folded works in this category.
             * @default 0
             */
            count: number;
            /**
             * Label
             * @description English label.
             */
            label: string;
            /**
             * Label Ar
             * @description Arabic label.
             */
            label_ar: string;
            /**
             * Slug
             * @description URL-safe identifier, e.g. 'shia-hadith-fiqh'.
             */
            slug: string;
            /**
             * Tradition
             * @description Sunni, Shia, or shared/neutral.
             * @default shared
             * @enum {string}
             */
            tradition: "sunni" | "shia" | "shared";
            /**
             * Volume Count
             * @description Physical volumes in this category.
             * @default 0
             */
            volume_count: number;
        };
        /**
         * CategoryFacet
         * @description How many matches a category holds, for the category filter.
         */
        CategoryFacet: {
            /**
             * Count
             * @description Matching pages in this category.
             */
            count: number;
            /**
             * Slug
             * @description Category slug (resolve label via the domain taxonomy).
             */
            slug: string;
        };
        /**
         * CorpusMatch
         * @description One full-text hit: the book it occurs in, the page, and an excerpt.
         */
        CorpusMatch: {
            /**
             * Author
             * @description Romanized author of the book, if known.
             */
            author?: string | null;
            /**
             * Category
             * @description Category slug; resolve via domain taxonomy.
             * @default
             */
            category: string;
            /**
             * Page
             * @description Page the match occurs on.
             */
            page: number;
            /**
             * Snippet
             * @description Excerpt of the matching page, Arabic.
             */
            snippet: string;
            /**
             * Title Ar
             * @description Arabic title of the book.
             */
            title_ar: string;
            /**
             * Title En
             * @description English title, if available.
             */
            title_en?: string | null;
            /**
             * Urn
             * @description URN of the matching book (opens in the reader).
             */
            urn: string;
            /**
             * Volume
             * @description Volume number, if known.
             */
            volume?: number | null;
        };
        /**
         * CrossRef
         * @description Pointer to a parallel narration in another collection.
         */
        CrossRef: {
            /**
             * Book
             * @description Source book (English transliteration).
             */
            book: string;
            /**
             * Book Ar
             * @description Source book (Arabic).
             */
            book_ar: string;
            /**
             * Chapter
             * @description Chapter or volume reference.
             */
            chapter: string;
            /**
             * Page
             * @description Page number in the source book.
             */
            page?: number | null;
        };
        /**
         * Daily
         * @description Top-level Daily payload: today's selection from each pool.
         */
        Daily: {
            book: components["schemas"]["DailyBookPick"];
            hadith: components["schemas"]["DailyHadith"];
            verse: components["schemas"]["Verse"];
        };
        /**
         * DailyBookPick
         * @description The 'book of the day' pick.
         */
        DailyBookPick: {
            open_to: components["schemas"]["OpenTo"];
            /** Rationale */
            rationale: string;
            /** Urn */
            urn: string;
        };
        /**
         * DailyHadith
         * @description Hadith of the day with source + parallels + grade.
         */
        DailyHadith: {
            /**
             * Grade
             * @enum {string}
             */
            grade: "sahih" | "hasan" | "daif" | "mawdu";
            /** Grade Label */
            grade_label: string;
            /** Isnad Ar */
            isnad_ar: string;
            /** Matn Ar */
            matn_ar: string;
            /** Matn En */
            matn_en: string;
            /** Note */
            note: string;
            /** Parallels */
            parallels: components["schemas"]["HadithParallel"][];
            source: components["schemas"]["HadithSource"];
        };
        /**
         * Domain
         * @description One top-level domain of knowledge (e.g. Hadith, Fiqh, Theology).
         */
        Domain: {
            /**
             * Blurb
             * @description One-sentence editorial summary of the domain.
             */
            blurb: string;
            /**
             * Categories
             * @description Categories grouped under this domain.
             */
            categories: components["schemas"]["Category"][];
            /**
             * Id
             * @description Domain id, e.g. 'hadith'.
             */
            id: string;
            /**
             * Label
             * @description English label.
             */
            label: string;
            /**
             * Label Ar
             * @description Arabic label.
             */
            label_ar: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hadith
         * @description One hadith record: isnad + matn + narrators + cross-references.
         */
        Hadith: {
            /**
             * Cross Refs
             * @description Parallel narrations.
             */
            cross_refs?: components["schemas"]["CrossRef"][];
            /**
             * Grade
             * @description Authenticity grade. None when the page is raw corpus text that the pipeline has not yet graded; the UI hides the grade pill in that case.
             */
            grade?: ("sahih" | "hasan" | "daif" | "mawdu") | null;
            /**
             * Isnad Ar
             * @description Chain of transmission in Arabic.
             */
            isnad_ar: string;
            /**
             * Matn Ar
             * @description Body of the hadith in Arabic.
             */
            matn_ar: string;
            /**
             * Matn En
             * @description English translation of the matn.
             */
            matn_en?: string | null;
            /**
             * N
             * @description Sequence number on the page.
             */
            n: number;
            /**
             * Narrators
             * @description Narrators in the chain.
             */
            narrators: components["schemas"]["Narrator"][];
        };
        /**
         * HadithParallel
         * @description A parallel narration in another collection.
         */
        HadithParallel: {
            /** Book */
            book: string;
            /** Book Ar */
            book_ar: string;
            /**
             * N
             * @description Report number within the source (often non-integer like '1/34/h.1').
             */
            n: string;
            /** Page */
            page?: number | null;
            /** Sect */
            sect: string;
            /** Urn */
            urn?: string | null;
        };
        /**
         * HadithSource
         * @description The originating book of a hadith of the day.
         */
        HadithSource: {
            /** Book */
            book: string;
            /** Book Ar */
            book_ar: string;
            /**
             * N
             * @description Report number within the source (often non-integer like '1/34/h.1').
             */
            n: string;
            /** Page */
            page?: number | null;
            /** Sect */
            sect: string;
            /** Urn */
            urn?: string | null;
        };
        /**
         * HistoryEvent
         * @description One chronicle entry keyed to a Hijri month + day.
         */
        HistoryEvent: {
            /** Day */
            day: number;
            /** Detail */
            detail: string;
            /** En */
            en: string;
            /** Month */
            month: number;
            /**
             * Year Ah
             * @description 0 marks an event before the hijra.
             */
            year_ah: number;
        };
        /**
         * Narrator
         * @description One narrator in an isnad.
         */
        Narrator: {
            /**
             * Canonical Id
             * @description Registry link: id in /api/canonical, when the name resolved to a canonical profile instead of a rijal entry. Mutually exclusive with rijal_id.
             */
            canonical_id?: number | null;
            /**
             * D
             * @description Death year, Hijri.
             */
            d?: number | null;
            /**
             * Grade
             * @description Biographical evaluation (Trustworthy, Reliable, ...).
             */
            grade: string;
            /**
             * Name
             * @description Name in romanized form.
             */
            name: string;
            /**
             * Name Ar
             * @description Name in Arabic.
             */
            name_ar: string;
            /**
             * Rijal Id
             * @description Registry link: id in /api/rijal, resolved at build time by normalized-name match. None when the registry does not know this narrator; the reader shows the name unlinked rather than guessing.
             */
            rijal_id?: number | null;
            /**
             * Role
             * @description Role / position in the chain (companion, transmitter, ...).
             */
            role: string;
        };
        /**
         * Observance
         * @description One recurring date in the Hijri year.
         */
        Observance: {
            /** Ar */
            ar: string;
            /** Day */
            day: number;
            /** En */
            en: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "eid" | "mourning" | "birth" | "night" | "observance";
            /** Month */
            month: number;
        };
        /**
         * OpenTo
         * @description Where to open the recommended book.
         */
        OpenTo: {
            /** Chapter En */
            chapter_en: string;
            /** Page */
            page: number;
        };
        /** Page[Ayah] */
        Page_Ayah_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["Ayah"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[BookSearchMatch] */
        Page_BookSearchMatch_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["BookSearchMatch"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[Book] */
        Page_Book_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["Book"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[CanonicalEntry] */
        Page_CanonicalEntry_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["CanonicalEntry"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[CorpusMatch] */
        Page_CorpusMatch_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["CorpusMatch"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[RijalEntry] */
        Page_RijalEntry_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["RijalEntry"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /** Page[Work] */
        Page_Work_: {
            /**
             * Items
             * @description Records in this slice.
             */
            items: components["schemas"]["Work"][];
            /**
             * Limit
             * @description Slice size requested.
             */
            limit: number;
            /**
             * Offset
             * @description Number of records skipped before this slice.
             */
            offset: number;
            /**
             * Total
             * @description Total records matching the query, across all pages.
             */
            total: number;
        };
        /**
         * RijalEntry
         * @description One narrator in the rijal registry (reliability-graded).
         */
        RijalEntry: {
            /**
             * Birth Year
             * @description Birth year as recorded (Hijri, free-form).
             * @default
             */
            birth_year: string;
            /**
             * Book Path
             * @description Relative path of the source corpus file.
             * @default
             */
            book_path: string;
            /**
             * Category
             * @description Data-quality class (clean, editorial).
             * @default clean
             */
            category: string;
            /**
             * Death Year
             * @description Death year as recorded (Hijri, free-form).
             * @default
             */
            death_year: string;
            /**
             * Evaluator
             * @description Critic who issued the reliability term.
             * @default
             */
            evaluator: string;
            /**
             * Full Name
             * @description Full name in Arabic.
             */
            full_name: string;
            /**
             * Id
             * @description Stable corpus index, also the detail-route key.
             */
            id: number;
            /**
             * Kunya
             * @description Teknonym (Abu/Umm ...), if recorded.
             * @default
             */
            kunya: string;
            /**
             * Nisba
             * @description Attributive name (tribe/place), if recorded.
             * @default
             */
            nisba: string;
            /**
             * Reliability Grade
             * @description Numeric reliability grade, as text.
             * @default
             */
            reliability_grade: string;
            /**
             * Reliability Term
             * @description Primary reliability term (thiqa, ...).
             * @default
             */
            reliability_term: string;
            /**
             * Source Label
             * @description Human label of the source work + volume.
             * @default
             */
            source_label: string;
            /**
             * Student Count
             * @description Number of recorded students.
             */
            student_count: number;
            /**
             * Teacher Count
             * @description Number of recorded teachers.
             */
            teacher_count: number;
            /**
             * Tradition
             * @description Sunni / shia / both, when classified.
             * @default
             */
            tradition: string;
        };
        /**
         * SearchFacets
         * @description Drill-down filters for the current query: categories, then books within
         *     the chosen category, then volumes within the chosen book.
         */
        SearchFacets: {
            /**
             * Books
             * @description Books in the chosen category, by count desc.
             */
            books: components["schemas"]["BookFacet"][];
            /**
             * Categories
             * @description Categories with matches, by count desc.
             */
            categories: components["schemas"]["CategoryFacet"][];
            /**
             * Volumes
             * @description Volumes in the chosen book, ascending.
             */
            volumes: components["schemas"]["VolumeFacet"][];
        };
        /**
         * Surah
         * @description One full surah: its numbered ayat in recitation order.
         *
         *     The dedicated Qurʾān reader consumes whole surahs; the longest (al-Baqara,
         *     286 ayat) is small enough that the full run ships in one response rather
         *     than a paged envelope.
         */
        Surah: {
            /**
             * Surah
             * @description Surah number.
             */
            surah: number;
            /**
             * Verse Count
             * @description Total ayat in the surah.
             */
            verse_count: number;
            /**
             * Verses
             * @description The surah's numbered ayat, in order.
             */
            verses: components["schemas"]["Ayah"][];
        };
        /**
         * Tafsir
         * @description One tafsir excerpt attached to the verse of the day.
         */
        Tafsir: {
            /** Author */
            author: string;
            /** Book */
            book: string;
            /** Book Ar */
            book_ar: string;
            /** Excerpt Ar */
            excerpt_ar: string;
            /** Excerpt En */
            excerpt_en: string;
            /** Page */
            page?: number | null;
            /** Urn */
            urn?: string | null;
        };
        /**
         * Toc
         * @description The full table of contents for one book.
         */
        Toc: {
            /**
             * Book Urn
             * @description URN of the book this TOC belongs to.
             */
            book_urn: string;
            /**
             * Entries
             * @description Ordered TOC rows.
             */
            entries: components["schemas"]["TocEntry"][];
        };
        /**
         * TocEntry
         * @description One row in a book's table of contents.
         */
        TocEntry: {
            /**
             * Active
             * @description Whether this is the section currently being read.
             * @default false
             */
            active: boolean;
            /**
             * Page
             * @description Page number where this section begins.
             */
            page: number;
            /**
             * Title
             * @description Arabic section title.
             */
            title: string;
            /**
             * Title En
             * @description English section title, if translated.
             */
            title_en?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verse
         * @description Verse of the day as served: the pool curation plus the canonical text.
         */
        Verse: {
            /** Ayah Ar */
            ayah_ar: string;
            /** Ayah En */
            ayah_en?: string | null;
            /** Ayah N */
            ayah_n: number;
            /** Surah N */
            surah_n: number;
            /** Tafsirs */
            tafsirs: components["schemas"]["Tafsir"][];
        };
        /**
         * VolumeFacet
         * @description How many matches a volume number holds, for the volume filter.
         */
        VolumeFacet: {
            /**
             * Count
             * @description Matching pages in this volume.
             */
            count: number;
            /**
             * Volume
             * @description Volume number present in the results.
             */
            volume: number;
        };
        /**
         * Work
         * @description One work, folded across the volumes that share its URN stem. ``page_count``
         *     is summed across the folded volumes.
         */
        Work: {
            /**
             * Author
             * @description Author in romanized form.
             */
            author?: string | null;
            /**
             * Author Ar
             * @description Author in Arabic.
             */
            author_ar: string;
            /**
             * Canonical
             * @description Editorial rank, or None.
             */
            canonical?: ("primary_reference" | "primary" | "secondary" | "tertiary") | null;
            /**
             * Canonical Tier
             * @description Editorial-rank tier derived from `canonical`, 0 = most authoritative; null when unranked. Served so client-side ordering and server-side `sort=canonical` paging share one tier table instead of each owning a copy.
             */
            readonly canonical_tier: number | null;
            /**
             * Category
             * @description Category slug (matches Domain.categories[].slug).
             */
            category: string;
            /**
             * Death Year Ah
             * @description Author's death year, Hijri (unknown is None, never a sentinel).
             */
            death_year_ah?: number | null;
            /**
             * Death Year Ce
             * @description Author's death year, CE.
             */
            death_year_ce?: number | null;
            /**
             * First Urn
             * @description URN of the first volume; opening the work opens this.
             */
            first_urn: string;
            /**
             * Page Count
             * @description Page count, if known.
             */
            page_count?: number | null;
            /**
             * Sect
             * @description Sect tagging (Imami, Sunni, etc.).
             */
            sect?: string | null;
            /**
             * Stem
             * @description URN stem shared by the work's volumes; the work key.
             */
            stem: string;
            /**
             * Title Ar
             * @description Arabic title.
             */
            title_ar: string;
            /**
             * Title En
             * @description English title, if available.
             */
            title_en?: string | null;
            /**
             * Volume Count
             * @description Number of volumes folded into this work.
             */
            volume_count: number;
            /**
             * Volumes
             * @description Member volume URNs, ordered by volume number.
             */
            volumes: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_almanac_api_almanac_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Almanac"];
                };
            };
        };
    };
    _list_books_api_books_get: {
        parameters: {
            query?: {
                /** @description Filter by category slug. */
                category?: string | null;
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Book_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_books__book_urn__pages__page_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_urn: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _search_book_api_books__book_urn__search_get: {
        parameters: {
            query?: {
                /** @description Arabic query; folded before matching. */
                q?: string;
                /** @description Matches per page. */
                limit?: number;
                /** @description Matches to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                book_urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BookSearchMatch_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_toc_api_books__book_urn__toc_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Toc"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__urn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_volumes_api_books__urn__volumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                urn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_canonical_api_canonical_get: {
        parameters: {
            query?: {
                /** @description Substring match on name / kunya / nisba. */
                q?: string;
                /** @description Only profiles merged from more than one raw entry. */
                merged_only?: boolean;
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CanonicalEntry_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canonical_api_canonical__canonical_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canonical_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Daily"];
                };
            };
        };
    };
    list_domains_api_domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
        };
    };
    _search_verses_api_quran_search_get: {
        parameters: {
            query?: {
                /** @description Arabic term or phrase to find in the Qurʾān. */
                q?: string;
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Ayah_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surah_api_quran__surah__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surah: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Surah"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verse_api_quran__surah___ayah__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surah: number;
                ayah: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ayah"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_rijal_api_rijal_get: {
        parameters: {
            query?: {
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
                /** @description Substring match on name / kunya / nisba. */
                q?: string;
                /** @description Filter by tradition (sunni / shia / both). */
                tradition?: string;
                /** @description Filter by data-quality category. */
                category?: string;
                /** @description Only entries with at least one teacher. */
                has_teachers?: boolean;
                /** @description Only entries carrying a reliability term. */
                has_reliability?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RijalEntry_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rijal_api_rijal__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RijalEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _search_api_search_get: {
        parameters: {
            query?: {
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
                /** @description Arabic phrase; folded before matching. */
                q?: string;
                /** @description Match mode: 'exact' (whole phrase) or 'broad' (sub-phrases). */
                mode?: "exact" | "broad";
                /** @description Restrict to these category slugs (repeatable; values OR together). */
                category?: string[] | null;
                /** @description Restrict to a book title (a work). */
                book?: string;
                /** @description Restrict to a volume number (0 = any). */
                volume?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CorpusMatch_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _search_facets_api_search_facets_get: {
        parameters: {
            query?: {
                /** @description Arabic phrase; folded before matching. */
                q?: string;
                /** @description Match mode: 'exact' (whole phrase) or 'broad' (sub-phrases). */
                mode?: "exact" | "broad";
                /** @description Restrict to these category slugs (repeatable; values OR together). */
                category?: string[] | null;
                /** @description Book to scope volume facets to. */
                book?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_works_api_works_get: {
        parameters: {
            query?: {
                /** @description Filter by category slug. */
                category?: string | null;
                /** @description Filter by domain id. */
                domain?: string | null;
                /** @description Tradition: sunni, shia, or shared. */
                tradition?: string | null;
                /** @description Filter to a canonical rank. */
                canonical?: ("primary_reference" | "primary" | "secondary" | "tertiary") | null;
                /** @description Search works by title or author. */
                q?: string;
                /** @description Ordering: canonical (rank tier, then death year), death_year_ah (undated last), title_ar, or volume_count. */
                sort?: ("canonical" | "death_year_ah" | "title_ar" | "volume_count") | null;
                /** @description Records per page. */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Work_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    _livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    _readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
